version: '3.8'

services:
  interview-ai:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/tmp/interview_ai_shared
    environment:
      - FLASK_ENV=production

volumes:
  shared_data:
